name: Hook-A-Duck

permissions:
  packages: read
  contents: write

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: Prod
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true

      - name: Update all modules
        run: hugo mod get -u

      - name: Build
        run: hugo --minify

#      - name: Deployer
#        uses: actions/upload-artifact@master
#        with:
#          name: website
#          path: './public'

      - name: Deploy
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Workflow commit of ./public
          file_pattern: public/*
          commit_user_name: Karl Austin
          commit_user_email: karl@karlaustin.com

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
